# Generated by Django 3.2.7 on 2021-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('standort', models.CharField(max_length=200)),
                ('modus', models.CharField(max_length=200)),
                ('teammitglieder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spieler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
