# Generated by Django 3.2.7 on 2021-10-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='standort',
            field=models.CharField(default='Berlin', max_length=200),
        ),
        migrations.AlterField(
            model_name='spiel',
            name='datetime',
            field=models.CharField(max_length=200),
        ),
    ]
