# Generated by Django 3.2.7 on 2021-10-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicker_app', '0002_auto_20211012_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spiel',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Spieler',
            new_name='Player',
        ),
    ]
