# Generated by Django 3.2.7 on 2021-10-15 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicker_app', '0003_auto_20211012_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='modus',
        ),
        migrations.RemoveField(
            model_name='game',
            name='teammitglieder',
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.CharField(default='Max Mustermann', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.CharField(default='Max Mustermann', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='player3',
            field=models.CharField(default='Max Mustermann', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='player4',
            field=models.CharField(default='Max Mustermann', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='posP1',
            field=models.CharField(default='vorne/hinten', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='posP2',
            field=models.CharField(default='vorne/hinten', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='posP3',
            field=models.CharField(default='vorne/hinten', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='posP4',
            field=models.CharField(default='vorne/hinten', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='winner1',
            field=models.CharField(default='Max Mustermann', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='standort',
            field=models.CharField(default='Berlin', max_length=200),
        ),
    ]
