# Generated by Django 3.2.7 on 2021-10-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicker_app', '0005_game_winner2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.CharField(default='YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]', max_length=200),
        ),
    ]
